### ISSUE TITLE
Broken link in https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/master/README.md

### ISSUE THREAD

**Issue by banshee** [nomiclabs/hardhat-ts-plugin-boilerplate#18]
https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/master/README.md has a link to https://hardhat.org/guides/create-plugin.html.  That link returns 404, and it's not clear where the link should point.

**Comment by fvictorio** [comment]
Thanks for letting us know about this @banshee :+1:
